workflows:
  react-native-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: latest
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npx expo prebuild
          npx expo build:android -t apk
    artifacts:
      - android/app/build/outputs/**/*.apk
